"""add user approval_status for admin approval flow

Revision ID: 15f5388d4cf8
Revises: 6082800cfafd
Create Date: 2026-08-16 13:54:37.792058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15f5388d4cf8'
down_revision = '6082800cfafd'
branch_labels = None
depends_on = None


def upgrade():
    # Create the enum type first
    op.execute("CREATE TYPE user_approval_status AS ENUM ('pending', 'approved', 'rejected')")
    
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approval_status', sa.Enum('pending', 'approved', 'rejected', name='user_approval_status'), nullable=False, server_default='pending'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('approval_status')
    
    # Drop the enum type
    op.execute("DROP TYPE IF EXISTS user_approval_status")

    # ### end Alembic commands ###