"""add processed_events table for webhook idempotency

Revision ID: 6082800cfafd
Revises: 660ae5267009
Create Date: 2026-08-16 01:10:20.952344

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6082800cfafd'
down_revision = '660ae5267009'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processed_events',
    sa.Column('event_id', sa.Text(), nullable=False),
    sa.Column('gateway', sa.String(length=20), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('processed_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_processed_events_event_id'), ['event_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processed_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_processed_events_event_id'))

    op.drop_table('processed_events')
    # ### end Alembic commands ###
