"""add failed_login_attempts locked_until password_history to users

Revision ID: 660ae5267009
Revises: 770a861fb02c
Create Date: 2026-08-16 00:55:55.306323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '660ae5267009'
down_revision = '770a861fb02c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_sessions', schema=None) as batch_op:
        batch_op.alter_column('class_id',
               existing_type=sa.BIGINT(),
               nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('failed_login_attempts', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('password_history', sa.JSON(), nullable=True))

    # تحديث الصفوف الموجودة بقيم افتراضية
    op.execute("UPDATE users SET failed_login_attempts = 0 WHERE failed_login_attempts IS NULL")
    op.execute("UPDATE users SET password_history = '[]'::json WHERE password_history IS NULL")

    # جعل الأعمدة NOT NULL بعد التحديث
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('failed_login_attempts', nullable=False)
        batch_op.alter_column('password_history', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('password_history')
        batch_op.drop_column('locked_until')
        batch_op.drop_column('failed_login_attempts')

    with op.batch_alter_table('ai_sessions', schema=None) as batch_op:
        batch_op.alter_column('class_id',
               existing_type=sa.BIGINT(),
               nullable=False)

    # ### end Alembic commands ###