"""M2T: جداول الدروس الخصوصية

Revision ID: 770a861fb02c
Revises: 024d12c3b6b2
Create Date: 2026-08-15 12:09:11.700235

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '770a861fb02c'
down_revision = '024d12c3b6b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tutor_profiles',
    sa.Column('tutor_id', sa.BigInteger(), nullable=False),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('grade_levels', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('price_hour', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_session', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('mode', sa.String(length=10), nullable=False),
    sa.Column('availability', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('invite_code', postgresql.CITEXT(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tutor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invite_code'),
    sa.UniqueConstraint('tutor_id')
    )
    op.create_table('tutoring_requests',
    sa.Column('tutor_id', sa.BigInteger(), nullable=False),
    sa.Column('student_id', sa.BigInteger(), nullable=False),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('preferred_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mode', sa.String(length=10), nullable=False),
    sa.Column('price_quote', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tutor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tutor_id', 'student_id', 'status', name='uq_tutoring_request_open')
    )
    with op.batch_alter_table('tutoring_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tutoring_requests_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tutoring_requests_tutor_id'), ['tutor_id'], unique=False)

    op.create_table('tutoring_sessions',
    sa.Column('request_id', sa.BigInteger(), nullable=True),
    sa.Column('tutor_id', sa.BigInteger(), nullable=False),
    sa.Column('student_id', sa.BigInteger(), nullable=False),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_min', sa.Integer(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('mode', sa.String(length=10), nullable=False),
    sa.Column('online_link', sa.Text(), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('payment_status', sa.String(length=10), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['tutoring_requests.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tutor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tutoring_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tutoring_sessions_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tutoring_sessions_tutor_id'), ['tutor_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tutoring_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tutoring_sessions_tutor_id'))
        batch_op.drop_index(batch_op.f('ix_tutoring_sessions_student_id'))

    op.drop_table('tutoring_sessions')
    with op.batch_alter_table('tutoring_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tutoring_requests_tutor_id'))
        batch_op.drop_index(batch_op.f('ix_tutoring_requests_student_id'))

    op.drop_table('tutoring_requests')
    op.drop_table('tutor_profiles')
    # ### end Alembic commands ###
